config/routes.rb
Rails.application.routes.draw do

  get '/login' => 'admin/sessions#new'
  get '/logout' => 'admin/sessions#destroy'

  namespace :admin do
    resources :moderators, only: [:index, :edit, :update]
    resources :sessions, only: [:new, :create, :destroy]
    resources :members
  end

end

app/models/fixture.rb
class Fixture < ActiveRecord::Base
  belongs_to :team
end

app/models/member.rb
class Member < ActiveRecord::Base
	belongs_to :teams
end

app/models/moderator.rb
class Moderator < ActiveRecord::Base
	has_secure_password

	validates :username, presence: true
	validates :forename, presence: true
	validates :surname, presence: true
	validates :password, presence: true

end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :fixture
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :members
  has_many :fixtures

  has_attached_file :team_photo, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :team_photo, :content_type => /\Aimage\/.*\Z/
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	before_action :authorize

	def current_moderator
		@moderator ||= Moderator.find(session[:current_moderator_id]) if session[:current_moderator_id]
	end

	def authorize
		unless current_moderator
			redirect_to '/login', alert: 'Please login to view admin panel'
		end
	end
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < Admin::ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def show
  end

  def destroy
  end
end

app/controllers/admin/moderators_controller.rb
class Admin::ModeratorsController < Admin::ApplicationController
	def index
		@moderators = Moderator.all
	end

	def edit
		@moderator = Moderator.find(params[:id])
	end

	def update
		@moderator = Moderator.find(params[:id])
		if @moderator.update(moderator_params)
			flash[:notice] = "Moderator was successfully updated"
			redirect_to admin_moderators_url
		else
			flash[:alert] = "There was a problem updating Moderator"
			render 'edit'
		end
	end

	private
		def moderator_params
		params.require(:moderator).permit(:id, :forename, :surname, :password)
		end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::ApplicationController
  before_action :authorize, except: [:new, :create]

  def new
  end

  def create
  	@moderator = Moderator.find_by(username: params[:username]).try(:authenticate, params[:password])
  	if @moderator
	  	session[:current_moderator_id] = @moderator.id
	  	redirect_to admin_moderators_url, notice: 'You have logged in successfully'
	else
		flash[:alert] = 'There was a problem with your username or password'
		render :new
	end
  end

  def destroy
  	session[:current_moderator_id] = nil
  	redirect_to '/login', notice: 'You have logged out successfully'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/members/edit.html.erb
<h1>Admin::Members#edit</h1>
<p>Find me in app/views/admin/members/edit.html.erb</p>

app/views/admin/members/index.html.erb
<h1>Members Index</h1>

app/views/admin/members/new.html.erb
<h1>Admin::Members#new</h1>
<p>Find me in app/views/admin/members/new.html.erb</p>

app/views/admin/members/show.html.erb
<h1>Admin::Members#show</h1>
<p>Find me in app/views/admin/members/show.html.erb</p>

app/views/admin/moderators/edit.html.erb
<h1>Edit Moderator</h1>

<% if @moderator.errors.any? %>
  <div id="validation_errors">
    <h2><%= pluralize(@moderator.errors.count, "error") %> prohibited this moderator from being saved:</h2>
 
    <ul>
    <% @moderator.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [:admin, @moderator] do |f| %>
	<p>
		<%= f.label :username %>
		<%= f.text_field :username %>
	</p>
	<p>
		<%= f.label :forename %>
		<%= f.text_field :forename %>
	</p>
	<p>
		<%= f.label :surname %>
		<%= f.text_field :surname %>
	</p>
	<p>	
		<%= f.label :password %>
		<%= f.password_field :password %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/admin/moderators/index.html.erb
<h1>Moderator's Index</h1>

<table class="table table-bordered table-hover">
	<thead>
		<tr>
			<th>Username</th>
			<th>Forename</th>
			<th>Surname</th>
			<th>Created At</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @moderators.each do|moderator| %>
			<tr>
				<td><%= moderator.username %></td>
				<td><%= moderator.forename %></td>
				<td><%= moderator.surname %></td>
				<td><%= time_ago_in_words(moderator.created_at) %> ago</td>
				<td><%= link_to 'Edit' , edit_admin_moderator_path(moderator) %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SportsTeamWebsite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notice] %>
	<div class="notice"><%= flash[:notice] %></div>
<% end %>

<% if flash[:alert] %>
	<div class="alert"><%= flash[:alert] %></div>
<% end %>

<%= link_to 'Log Out', logout_path %>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SportsTeamWebsite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notice] %>
	<div class="notice"><%= flash[:notice] %></div>
<% end %>

<% if flash[:alert] %>
	<div class="alert"><%= flash[:alert] %></div>
<% end %>

<%= yield %>

</body>
</html>